### ISSUE TITLE
Adding a Setting for Multisite Usage

### ISSUE THREAD

**Issue by ulliholtgrave** [Pantsoffski/Author-Chat-Plugin#4]
Hey, 
do you have any kind of code guidelines for your project? We are using your Plugin in our multisite installation and want to add a little feature :)
Btw: great job developing that plugin! :+1:

**Comment by Pantsoffski** [comment]
Hello,
thanks for kind words :) Unfortunately I don't have any code guidelines for that project, only few comments in code... Multisite support is a great idea for that plugin, but right now I really don;t have time to develop it...

**Comment by ulliholtgrave** [comment]
Hey Piotr,
we are already customizing your Plugin in such way, that it is able to be used on multi-site environments. If it is okay for you, we will develop some additional setting to provide it in an dynamic way and would create a PR on this Repo within the next two weeks :)
If the changes fits your expectations you might add them to your Plugin core 
Cheers, Ulli

**Comment by Pantsoffski** [comment]
Hi Ulli,
it's really great news, this plugin is one of my first useful things in a developer career, so I'm very happy that Author Chat is so good for so many people. Waiting for your code, and sure - I'm going to add it to plugin core in future or use it to develop something new :) Thank you!
Best wishes,
Piotr
