### ISSUE TITLE
Update isn't working 1.8.1

### ISSUE THREAD

**Issue by PaulBG2** [Pantsoffski/Author-Chat-Plugin#5]
Updated Author Chat plugin on WP now the Dashboard link has disappeared? Cannot open Author Chat. Settings and Users Online are there?

**Comment by Pantsoffski** [comment]
Author Chat link on left column was removed from dashboard in new version, but you should see Author Chat window at Dashboard view - if not try to check Author Chat in Screen Options (above dashboard view). If nothing helps, uninstall Author Chat then install again, should work.

**Comment by PaulBG2** [comment]
I can see a small box at the bottom of the Dashboard home page but it is too hard to use on a phone. The old version gave a full page view, 1.6.0 ? I can't remember installed Nov '17. Is it possible to get the old version back please, as a zip

**Comment by Pantsoffski** [comment]
Try to use older version, you can find all versions here: https://wordpress.org/plugins/author-chat/advanced/ just scroll to bottom.

**Comment by PaulBG2** [comment]
Many thanks!

I’ve gone back to 1.7.5

It works for me, and retraining the admin people is just too much of a chore lol.

Paul
