### ISSUE TITLE
Buttons doesnt Work / Usersearchbar isnt visible

### ISSUE THREAD

**Issue by Nick64or** [Pantsoffski/Author-Chat-Plugin#6]
Hey,

we use the newest WP Version and Chrome / Firefox, i cant click on the + Button to add rooms when i klick on it, it do nothing. The Serachbar to add privat rooms with users isnt there...

Iam full admin of the Site ...

What i have to to ? ( I purchased premium !! )

**Comment by Pantsoffski** [comment]
Hello,
I'm sorry to hear that. There may be many reasons for this behavior. First of all try:
- uncheck “Show weekday names” checkbox in settings,
- enable/disable other plugins (One of installed plugins can interfere with Author Chat),
- disable any adblocker from your browser,
- try to install old versions of plugin (you can download them [HERE](https://wordpress.org/plugins/author-chat/advanced/) at the bottom of site).

I just checked the plugin twice and it works without problems, also no one else is reporting about something similar, so this i really odd.

**Comment by Nick64or** [comment]
I try it all - doesnt work.
Now i installed the newest one again and my Premium Feature is lost....
The Older Versions of your chat doesnt support private chatrooms i see but i need this...

**Comment by Nick64or** [comment]
ok .. magic ... now it works...

**Comment by Nick64or** [comment]
the bars and the problemes from bevore are solved... but now when i typed text and send it ... nothing appears in chat box

**Comment by Pantsoffski** [comment]
1.8.2 version has chat rooms, maybe download and install it. It sounds like some major problem with JS scripts on your server...

**Comment by Nick64or** [comment]
how can i fix this JS problem ?

**Comment by Pantsoffski** [comment]
have you tried 1.8.2?

**Comment by Nick64or** [comment]
With this version the text box works but not the bars and rooms...

**Comment by Pantsoffski** [comment]
I can't reproduce that behavior on my server. If you need help you have to create some author/guest account on your website, so I could log in and check it out.

**Comment by zwood123** [comment]
Hello,
I have the same problems.
You can write text. But the top buttons do not work.
And the worst thing is that the chat itself scrolls down, it is not possible to read.

The plugin is very good.
If only I hadn’t flipped down myself.
Private rooms are not needed =)

**Comment by Pantsoffski** [comment]
> 
> 
> Hello,
> I have the same problems.
> You can write text. But the top buttons do not work.
> And the worst thing is that the chat itself scrolls down, it is not possible to read.
> 
> The plugin is very good.
> If only I hadn’t flipped down myself.
> Private rooms are not needed =)

Hello,
thank you. I will check it out and try fix that bug with next update. I'm not PHP/Javascript master unfortunately, but trying to do my best =)
